version: '3.8'
services:
  client:
    restart: always
    build:
      args:
        REACT_APP_API_HOST: https://api.palettehub.net
        NGINX_CONF: nginx.conf
    ports:
      - "443:443"
    depends_on:
      - rest_api
    volumes:
      - certbot_conf:/etc/nginx/ssl:ro
      - certbot_var:/var/lib/letsencrypt:ro
      - certbot_data:/var/share/nginx/html/letsencrypt:ro
  rest_api:
    restart: always
    environment:
      CLIENT_WEB_ORIGIN: https://palettehub.net
  mysql:
    restart: always
  certbot:
    image: certbot/certbot:latest
    container_name: palette_hub_certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while true; do certbot renew; sleep 12h; done;'"
    restart: always
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - certbot_data:/var/www/palettehub
volumes:
  certbot_conf:
    name: palette_hub_certbot_conf_volume
  certbot_data:
    name: palette_hub_certbot_data_volume
  certbot_var:
    name: palette_hub_certbot_var_volume
secrets:
  db_api_pass:
    file: ${PALETTE_HUB_SECRETS}/mysql_api_pass.txt
  jwt_secret:
    file: ${PALETTE_HUB_SECRETS}/jwt_secret.txt
  db_root_pass:
    file: ${PALETTE_HUB_SECRETS}/mysql_root_pass.txt