version: '3.8'
services:
  client:
    restart: always
    build:
      args:
        REACT_APP_API_HOST: https://api.palettehub.net
        NGINX_CONF: nginx.conf
    ports:
      - "443:443"
    volumes:
      # - ./data/certbot/conf:/etc/letsencrypt
      - certbot_conf:/etc/nginx/ssl
      - certbot_data:/var/share/nginx/html/letsencrypt
  rest_api:
    restart: always
  mysql:
    restart: always
  certbot:
    image: certbot/certbot:latest
    container_name: palette_hub_certbot
    command: [certonly, --webroot, -w, /var/www/palettehub, -d, palettehub.net, -d, "*.palettehub.net", 
      --agree-tos, --force-renewal, --rsa-key-size, "4096", --email, palettehub.net@gmail.com]
    depends_on:
      - client
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_data:/var/www/palettehub
volumes:
  certbot_conf:
    name: palette_hub_certbot_conf_volume
  certbot_data:
    name: palette_hub_certbot_data_volume
secrets:
  db_api_pass:
    file: ${PALETTE_HUB_SECRETS}/mysql_api_pass.txt
  jwt_secret:
    file: ${PALETTE_HUB_SECRETS}/jwt_secret.txt
  db_root_pass:
    file: ${PALETTE_HUB_SECRETS}/mysql_root_pass.txt