version: '3.8'
services:
  client:
    build:
      context: client
      target: prod
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${PALETTE_HUB_GOOGLE_CLIENT_ID}
    container_name: palette_hub_client
    image: palette_hub_client
    ports:
      - "80:80"
      - "3000:3000"
    networks:
      - frontnet
  rest_api:
    build: 
      context: rest_api
      target: prod
    container_name: palette_hub_rest_api
    image: palette_hub_rest_api
    ports:
      - "${PALETTE_HUB_API_PORT}:8080"
    depends_on:
      - mysql
    networks:
      - backnet
      - frontnet
    environment:
      MYSQL_HOST: ${PALETTE_HUB_MYSQL_HOST}
      MYSQL_PORT: ${PALETTE_HUB_MYSQL_CONTAINER_PORT}
      MYSQL_DB: ${PALETTE_HUB_MYSQL_DATABASE}
      MYSQL_USER: ${PALETTE_HUB_MYSQL_API_USER}
      MYSQL_PASSWORD: /run/secrets/db_api_pass
      JWT_SECRET: /run/secrets/jwt_secret
      GOOGLE_CLIENT_ID: ${PALETTE_HUB_GOOGLE_CLIENT_ID}
      CLIENT_WEB_ORIGIN: ${PALETTE_HUB_CLIENT_WEB_ORIGIN}
    secrets:
      - jwt_secret
      - db_api_pass
    restart: on-failure
  mysql:
    image: mysql:8
    container_name: palette_hub_mysql
    ports:
      - "${PALETTE_HUB_MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      MYSQL_DATABASE: ${PALETTE_HUB_MYSQL_DATABASE}
      MYSQL_API_USER: ${PALETTE_HUB_MYSQL_API_USER}
      MYSQL_API_PASSWORD_FILE: /run/secrets/db_api_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
    secrets:
      - db_api_pass
      - db_root_pass
volumes:
  mysql-data:
    name: palette_hub_mysql_volume
networks:
  backnet:
    name: backnet
    driver: bridge
  frontnet:
    name: frontnet
    driver: bridge
secrets:
  db_api_pass:
    file: ${PALETTE_HUB_SECRETS_FOLDER}/mysql_api_pass.txt
  jwt_secret:
    file: ${PALETTE_HUB_SECRETS_FOLDER}/jwt_secret.txt
  db_root_pass:
    file: ${PALETTE_HUB_SECRETS_FOLDER}/mysql_root_pass.txt